INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_AD2_ANALOGIN_RECORD AD2_AnalogIn_Record)

FIND_PATH(
    AD2_ANALOGIN_RECORD_INCLUDE_DIRS
    NAMES AD2_AnalogIn_Record/api.h
    HINTS $ENV{AD2_ANALOGIN_RECORD_DIR}/include
        ${PC_AD2_ANALOGIN_RECORD_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    AD2_ANALOGIN_RECORD_LIBRARIES
    NAMES gnuradio-AD2_AnalogIn_Record
    HINTS $ENV{AD2_ANALOGIN_RECORD_DIR}/lib
        ${PC_AD2_ANALOGIN_RECORD_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/AD2_AnalogIn_RecordTarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(AD2_ANALOGIN_RECORD DEFAULT_MSG AD2_ANALOGIN_RECORD_LIBRARIES AD2_ANALOGIN_RECORD_INCLUDE_DIRS)
MARK_AS_ADVANCED(AD2_ANALOGIN_RECORD_LIBRARIES AD2_ANALOGIN_RECORD_INCLUDE_DIRS)
