INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_AD2_ANALOGOUT_SINE AD2_AnalogOut_Sine)

FIND_PATH(
    AD2_ANALOGOUT_SINE_INCLUDE_DIRS
    NAMES AD2_AnalogOut_Sine/api.h
    HINTS $ENV{AD2_ANALOGOUT_SINE_DIR}/include
        ${PC_AD2_ANALOGOUT_SINE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    AD2_ANALOGOUT_SINE_LIBRARIES
    NAMES gnuradio-AD2_AnalogOut_Sine
    HINTS $ENV{AD2_ANALOGOUT_SINE_DIR}/lib
        ${PC_AD2_ANALOGOUT_SINE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(AD2_ANALOGOUT_SINE DEFAULT_MSG AD2_ANALOGOUT_SINE_LIBRARIES AD2_ANALOGOUT_SINE_INCLUDE_DIRS)
MARK_AS_ADVANCED(AD2_ANALOGOUT_SINE_LIBRARIES AD2_ANALOGOUT_SINE_INCLUDE_DIRS)

