INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_AD2_ANALOGOUT_PLAY AD2_AnalogOut_Play)

FIND_PATH(
    AD2_ANALOGOUT_PLAY_INCLUDE_DIRS
    NAMES AD2_AnalogOut_Play/api.h
    HINTS $ENV{AD2_ANALOGOUT_PLAY_DIR}/include
        ${PC_AD2_ANALOGOUT_PLAY_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    AD2_ANALOGOUT_PLAY_LIBRARIES
    NAMES gnuradio-AD2_AnalogOut_Play
    HINTS $ENV{AD2_ANALOGOUT_PLAY_DIR}/lib
        ${PC_AD2_ANALOGOUT_PLAY_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(AD2_ANALOGOUT_PLAY DEFAULT_MSG AD2_ANALOGOUT_PLAY_LIBRARIES AD2_ANALOGOUT_PLAY_INCLUDE_DIRS)
MARK_AS_ADVANCED(AD2_ANALOGOUT_PLAY_LIBRARIES AD2_ANALOGOUT_PLAY_INCLUDE_DIRS)

